version: "3"

services:
  postgresdb:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password